README.md
script.bash
src/__init__.py
src/system/apps/base/installable_app.py
src/system/resources/ping.py
src/system/resources/updater.py
src/system/utils/file.py
systemd/nubeio-rubix-service.old-template.service

- `systemd` file using `lib`
- `python==3.5` support

Make old script.bash works for now

---

src/system/networking/network_info.py

Fix: network info get

---

pyproject.toml
src/reverse_proxy_routes.py

Bump new release

---

pyproject.toml
src/system/apps/base/frontend_app.py
src/system/apps/base/python_app.py
src/system/apps/constants/states.py
src/system/apps/constants/types.py
src/system/apps/enums/types.py
src/system/apps/rubix_plat_build_app.py
src/system/apps/wires_builds_app.py
src/system/resources/app/status.py
src/system/resources/service/service.py
src/system/utils/shell.py

- Issue fix for get release version

Issue fix for get release version

---

src/routes.py
src/system/resources/host_reboot.py
src/system/resources/service/utils.py

`http://${ip}:${port}/api/system/host/restart`
> HTTP POST
> body
>>action: restart

Host reboot

---

src/system/apps/base/frontend_app.py
src/system/resources/app/delete_data.py
src/system/systemd/systemd.py

- After delete DB files of Apps from /delete_data API Apps becomes unstable. So we need to restart our App.

Improvements on /delete_data

---

src/system/apps/base/frontend_app.py
src/system/apps/base/installable_app.py
src/system/apps/base/java_app.py
src/system/apps/base/python_app.py
src/system/resources/app/app.py

Resolves: #73
- Include an additional field `name`, `created_at`, `browser_download_url` available for:
- GET: `/api/app` &
- GET: `/api/app/stats/<string:app_service>`

Let user download the zip build

---

src/system/resources/app/app.py

-  Added try except block to pass any type exception from app.get_download_link(app_setting.token, True)

Improvement on /api/app

---

src/system/resources/app/control.py
src/system/resources/service/control.py
src/system/resources/service/utils.py

-  Added enable before starting and disable before stopping in api endpoints:
-   ```/api/system/service/control```
-   ```/api/app/control```

Improvement on start/stop Services/Apps

---

src/system/resources/host_info.py

update of host info

---

.gitignore
run.py
src/setting.py
src/system/apps/base/installable_app.py
src/system/resources/app/install.py

Resolves: CU-25eak0
- Added backup_data before installation in POST `api/app/install`

Backup existing data on upgrade/downgrade

---

poetry.lock
pyproject.toml
src/platform/resource_wires_plat.py
src/reverse_proxy_routes.py
src/system/networking/network.py
src/system/networking/ufw.py
src/system/resources/app/app.py
src/system/resources/app/control.py
src/system/resources/app/delete_data.py
src/system/resources/app/download.py
src/system/resources/app/install.py
src/system/resources/app/release.py
src/system/resources/app/stats.py
src/system/resources/app/token.py
src/system/resources/app/uninstall.py
src/system/resources/app/utils.py
src/system/resources/host_info.py
src/system/resources/host_reboot.py
src/system/resources/host_timezone.py
src/system/resources/ping.py
src/system/resources/service/control.py
src/system/resources/service/service.py
src/system/resources/service/stats.py
src/system/resources/service/utils.py
src/users/model_users.py
src/users/resource_login_users.py
src/users/resource_users.py

Resolves: CU-278n3j
- Implement `rubix-http` for standardizing HTTP error msg

Integrate rubix-http for better error response

---

README.md
run.py
src/server.py
src/setting.py

Resolves: CU-27bw55
-  Changed folder structure for data ,config and artifact files. Eg
-  <global_dir>/<data_dir>
-  <global_dir>/<config_dir>
-  <global_dir>/<artifact_dir>

Standardization of data convention

---

src/system/resources/fields.py
src/system/utils/shell.py

Resolves: #118
- Added **_is_enabled_** field on src/system/resources/fields.py > service_field to know whether service is currently enabled or disabled.

Add enable/disable for services

---

src/users/model_users.py

Resolves: #121
- Changed default password to `N00BWires`

Change default password

---

README.md
src/routes.py
src/system/apps/base/installable_app.py
src/system/apps/base/python_app.py
src/system/resources/app/upload.py
src/system/utils/file.py

Resolves: CU-2f903z
- Added `/api/services/upload` endpoint. Example:
```curl -X POST http://localhost:1616/api/app/upload -H "Content-Type: multipart/form-data" -F "service=<service>" -F "version=<version>" -F "file=<file>"```

Add upload artifacts option

---

README.md
src/routes.py
src/system/apps/base/installable_app.py
src/system/resources/app/download_data.py
src/system/utils/file.py

Resolves: #129
- Added endpoint `/api/app/download_data`. Examples:
```bash
curl -X GET http://localhost:1616/api/app/download_data  -H "Content-Type: application/json" -d '{"service":"POINT_SERVER"}' -o 'POINT_SERVER_DATA'
curl -X GET http://localhost:1616/api/app/download_data  -H "Content-Type: application/json" -d '{"service":"BACNET_SERVER"}' -o 'BACNET_SERVER_DATA'
curl -X GET http://localhost:1616/api/app/download_data  -H "Content-Type: application/json" -d '{"service":"LORA_RAW"}' -o 'LORA_RAW_DATA'
curl -X GET http://localhost:1616/api/app/download_data  -H "Content-Type: application/json" -d '{"service":"WIRES"}' -o 'WIRES_DATA'
curl -X GET http://localhost:1616/api/app/download_data  -H "Content-Type: application/json" -d '{"service":"RUBIX_PLAT"}' -o 'RUBIX_PLAT_DATA'
```

API: Download Database

---

poetry.lock
pyproject.toml
src/proxy/master_proxy_routes.py
src/proxy/slave_proxy_routes.py
src/proxy/slaves_broadcast_proxy_routes.py
src/proxy/slaves_multicast_proxy_routes.py

- Timeout argument support for master > slave proxy requests
For example: `http://localhost:1616/slaves/multicast/api/system/ping?timeout=10`
It waits for 10 sec. max.

Timeout arg support for master > slave proxy requests

---

config/apps.json
config/apps.master.json
src/system/apps/base/installable_app.py

- Added nubeio-rubix-app-modbus-py PythonApp.

Add nubeio-rubix-app-modbus-py

---

src/system/apps/base/installable_app.py
src/system/resources/app/uninstall.py
src/system/resources/app/utils.py

Resolves: #200 
- Changed  backup directory from `/data/backup/<app_data_dir>/<datetime>_<updated_version>` to `/data/backup/<app_data_dir>/<datetime>_<current_version>`

Improve backup directory

---

src/server.py

Resolves: #228 
- Clear download state (rubix apps and plugins) when we start this service

Clear download state when we start this service

---

src/system/apps/base/go_app.py

Resolves: #245
- Removed all installed plugins on app installation and copy all those downloaded plugins

Fix: plugins installation on upgrading app

---

src/app.py
src/bios/resources/clear_app_state.py
src/bios/utils.py
src/routes.py
src/server.py

Resolves: #246
- Added BIOS app state clear on app start
- Added DELETE `bios/clear_app_state` endpoint. Example:
-  DELETE `api/bios/clear_app_state`

Add BIOS app state clear

---

src/system/utils/file.py

Resolves: #284 
- In `wirte_file` -> check and create directory if does not exists.

Fix: No such file or directory
